### PR TITLE
Update config.go

### PR DESCRIPTION
**Pull request by amansx**

### CODE REVIEW

**Comment by amimof** [comment]
Hi, thanks for contributing. Can you provide more info on this. Also there seems to be a syntax error.

**Comment by amansx** [comment]
Hi, New fields added to the response by Phillips, 
tried running the code and Json unmarshal fails due to the missing fields, 
I don't see a syntax error can you suggest?

**Comment by amimof** [comment]
The travis build has failed with errors. 
https://travis-ci.org/amimof/huego/builds/495355893?utm_source=github_status&utm_medium=notification

What is the version of your Hue Bridge? What is it you are trying to marshal? Code and/or snippets would be useful.

**Comment by amimof** [comment]
Closing due to inactivity

**Pull request closed without merging**
